version: '3.9'

networks:
  default:
    driver: bridge
services:
  # SQL Server service
  db:
    # Docker Image for MSSQL
    image: mcr.microsoft.com/mssql/server
    container_name: db-sqlserver
    networks:
      - default
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your@Password
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  # SQL Server data volume
  sql_data:
    # Define the volume to persist SQL Server data